
jira_hostname=my-company.atlassian.net
jira_username=my-jira-user-name
jira_apikey=xxx
jira_active_state=In Development

work_per_day=PT7H30M
minimum_work_logged=PT30M
# Tasks with this much (or less) left of the estimate are filled up completely first
small_task_threshold=PT2H

rest_debug_log=false
rest_client_timeout=PT10S
